#!/bin/bash
. ../config/script_conf

cd ../dist
python $EGG_FILE_NAME STREAM_PRODUCER ${PRODUCER_NAME} ${KAFKA_BOOTSTRAP_SERVERS} ${KAFKA_INPUT_TOPIC_NAME} ${INPUT_JSON_FILE} ${KAFKA_PRODUCER_SLEEP_TIME} ${DB_FILE_PATH}
